In [1]:
import praw
import pandas as pd

In [2]:
reddit = praw.Reddit(client_id ='4iavd3DtyOMmyg',  
                     client_secret ='aPzAU3cr9yVMPIqVtfWVKwseGdQCQg',  
                     user_agent ='surya')

In [3]:
subreddit = reddit.subreddit('AskReddit')

In [4]:
new_python = subreddit.hot(limit=1000)

In [5]:
Title = []
Ups = []
Downs = []
Upvote_ratio = []
Score = []
Gilded =[]
Over_18 = []
Number_of_Comments = []
count = 0
for submission in new_python:
    if not submission.stickied:
        title = submission.title
        Title.append(title)
        
        ups = submission.ups
        Ups.append(ups)
        
        downs = submission.downs
        Downs.append(downs)
        
        upvoteratio = submission.upvote_ratio
        Upvote_ratio.append(upvoteratio)
        
        score = submission.score
        Score.append(score)
        
        gilded = submission.gilded
        Gilded.append(gilded)
        
        over_18 = submission.over_18
        Over_18.append(over_18)
        
        numberofcomments = submission.num_comments
        Number_of_Comments.append(numberofcomments)

In [6]:
df = pd.DataFrame()
df['Title'] = Title
df['Ups'] = Ups
df['Downs'] = Downs
df['Upvote_ratio'] = Upvote_ratio
df['Score'] = Score
df['Gilded'] = Gilded
df['Over_18'] = Over_18
df['Number_of_Comments'] = Number_of_Comments

In [7]:
df

,Title,Ups,Downs,Upvote_ratio,Score,Gilded,Over_18,Number_of_Comments
0,What's the most f*cked up thing you saw at a s...,40112,0,0.90,40112,1,True,11626
1,"[Serious] Men of Reddit, what are some questio...",3696,0,0.92,3696,0,False,4944
2,What cinematic death would have had the best o...,4213,0,0.97,4213,0,False,711
3,What is a NOT fun fact?,77810,0,0.85,77810,0,False,33082
4,"Apart from accent, how can you tell someone is...",6295,0,0.95,6295,0,False,6408
...,...,...,...,...,...,...,...,...
989,In what situations have you wanted someone to ...,3,0,1.00,3,0,False,6
990,"Dear people of Reddit, what do you order at Su...",10,0,0.81,10,0,False,81
991,Women of Reddit! What the best advice for when...,4,0,0.70,4,0,False,28
992,"You walk down the London roads, and out of now...",2,0,0.60,2,0,False,13
993,What would have been the equivalent of your jo...,3,0,1.00,3,0,False,16

In [9]:
df.to_csv('dataset.csv')

In [10]:
df.shape

(994, 8)